# Generated by Django 2.0.2 on 2018-02-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cBase', '0002_client_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Client_old',
        ),
    ]
