# Generated by Django 2.0.2 on 2018-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cBase', '0005_auto_20180219_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
